name: Persona Letter Backend CI/CD !

on:
  # main branch에 푸쉬할 때
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2a


    # 실제로 코드를 배포한다.
    - name: Code Deploy
      run: aws deploy create-deployment --application-name persona_letter --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name persona_letter_deploy
