name: Persona Letter Backend CI/CD !

on:
  # main branch에 푸쉬할 때
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to AWS EC2
      shell: bash
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} <<'EOF'
        
          # Kill existing uvicorn process
          pkill uvicorn || true

          # Navigate to the directory and remove existing repo
          cd ~/Persona_Letter
          sudo rm -r ~/Persona_Letter/Persona-Letter-Backend/

          # Clone the repository
          git clone https://github.com/A-IDLE/Persona-Letter-Backend.git

          # Navigate to the backend directory
          cd ~/Persona_Letter/Persona-Letter-Backend/

          # Install dependencies
          pip install -r requirements.txt

          # Copy configuration files
          cp ~/Persona_Letter/config/backend/* ~/Persona_Letter/Persona-Letter-Backend/
          cp ~/Persona_Letter/config/backend/.env ~/Persona_Letter/Persona-Letter-Backend/

          # Start uvicorn
          nohup uvicorn app.main:fastapi_app --host 0.0.0.0 --port 9000 --reload &
          
        EOF